# -*- coding: utf-8 -*-
"""CS 3341 Unit Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FIPcTLncFdY52qv7ITRfpzKg0aa9aT3
"""

class Student:
    def __init__(self, name, completed_assignments, total_assignments):
        self.name = name
        self.completed_assignments = completed_assignments
        self.total_assignments = total_assignments

    def calculate_student_progress(self):
        if self.total_assignments == 0:
            return 0
        return (self.completed_assignments / self.total_assignments) * 100

import unittest

class TestStudentProgress(unittest.TestCase):
    def test_normal_case(self):
        student = Student("Alice", 5, 10)
        self.assertEqual(student.calculate_student_progress(), 50)

    def test_boundary_case(self):
        student = Student("Bob", 10, 10)
        self.assertEqual(student.calculate_student_progress(), 100)

    def test_zero_case(self):
        student = Student("Charlie", 0, 10)
        self.assertEqual(student.calculate_student_progress(), 0)

    def test_edge_case(self):
        student = Student("David", 0, 0)
        self.assertEqual(student.calculate_student_progress(), 0)

if __name__ == '__main__':
    unittest.main(argv=[''], verbosity=2, exit=False)